url: https://greg.loris.uk
enforce_ssl: greg.loris.uk

markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-gist
  - jekyll-sitemap
sass:
  style: compressed
webrick:
  headers:
    X-Clacks-Overhead: GNU Terry Pratchett