title: Greg
subtitle: The CGS Calculator. Now for NCS!
description: Greg works out your current course marks and how much you'll need to get in the exam
author: Kit Maywood & looooris
og_image: /assets/og_image.jpg

url: https://greg.loris.uk
enforce_ssl: greg.loris.uk

markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-gist
  - jekyll-sitemap
sass:
  style: compressed
webrick:
  headers:
    X-Clacks-Overhead: GNU Terry Pratchett